#!/bin/bash 
cd holberton-system_engineering-devops
mkdir 0x01-shell_permissions
echo "#!/bin/bash" >>0-iam_betty
echo "#!/bin/bash" >>0-iam_betty
#!/bin/bash
cd holberton-system_engineering-devops
mkdir 0x01-shell_permissions
echo "#!/bin/bash" >>0-iam_betty
echo "#!/bin/bash" >>1-who_am_i
echo "#!/bin/bash" >>2-groups
echo "#!/bin/bash" >>3-new_owner
echo "#!/bin/bash" >>4-empty
echo "#!/bin/bash" >>5-execute
echo "#!/bin/bash" >>6-multiple_permissions
echo "#!/bin/bash" >>7-everybody
echo "#!/bin/bash" >>8-James_Bond
echo "#!/bin/bash" >>9-John_Doe
echo "#!/bin/bash" >>10-mirror_permissions
echo "#!/bin/bash" >>11-directories_permissions
echo "#!/bin/bash" >>12-directory_permissions
echo "#!/bin/bash" >>13-change_group
echo "#!/bin/bash" >>14-change_owner_and_group
echo "#!/bin/bash" >>15-symbolic_link_permissions
echo "#!/bin/bash" >>16-if_only
echo "#!/bin/bash" >>100-Star_Wars
echo "#!/bin/bash" >>101-man_holberton
git add *
git commit -m "shell_permissions"
git push origin master
