#!/usr/bin/env bash
# Serve a web page using nginx
apt -y update
apt -y upgrade
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "<html><body>Holberton School</body></html>" > /var/www/html/index.html
service nginx restart