#!/usr/bin/env bash
# nginx static server redirect
apt update -y
apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
STR="         location /redirect_me
        {
                return 301 https://www.youtube.com;

        }"
sed -i "s/server_name _/ $STR/g" /etc/nginx/sites-available/default
service nginx restart