FROM ubuntu 

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
RUN  apt-get update -y
RUN  apt-get upgrade -y
#RUN useradd -u 8877 Hector-docker-ubuntu
#RUN usermod -aG sudo Hector-docker-ubuntu
#RUN echo "Hector-docker-ubuntu ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/Hector-docker-ubuntu && \
	#	    chmod 0440 /etc/sudoers.d/Hector-docker-ubuntu
ENV LANG en_US.utf8
#RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
#USER Hector-docker-ubuntu
CMD ["/bin/bash"]