#!/usr/bin/env bash
#double the number of server by adding x-serverd-by headers to identify which webserver is 
apt update -y
apt upgrade -y
apt install haproxy -y
cd ~
mkdir config
source cd config/
echo "frontend http80
    bind *:80
    timeout client 60s
    mode http
    default_backend allservers

backend allservers
    timeout connect 10s
    timeout server 1000s
    mode http
    server web-01 34.74.33.180:80
    server web-01 34.224.32.83:80" >> config.cfg
haproxy -D -f config.cfg