#!/usr/bin/env bash
#use of read and cut in bash to read input

filename="/etc/passwd"

while IFS=: read -r username pass u_id g_id u_info home cmd
do
		echo "The user $username is part of the $g_id gang, lives in $home and rides $cmd. $u_id's place is protected by the passcode $pass, more info about the user here: $u_info"
done < "$filename"