#!/usr/bin/env bash
#use of read and cut in bash to read input

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7 || [[ -n $* ]]
do
	echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3 place is protected by the passcode $f2, more info about the user here: $f5"
done </etc/passwd