#!/usr/bin/env bash
#run nginx as nginx in docker container and
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx reload