#!/usr/bin/env bash
#run nginx as nginx in docker container and
nginx -s stop
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx nginx -s reload